/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct myString {
	char text[256];
};
typedef struct myString myString;

#define ZADANIE_2 0x23451112
#define ZADANIE_2_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define show 1
extern  void * show_1(myString *, CLIENT *);
extern  void * show_1_svc(myString *, struct svc_req *);
extern int zadanie_2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define show 1
extern  void * show_1();
extern  void * show_1_svc();
extern int zadanie_2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_myString (XDR *, myString*);

#else /* K&R C */
extern bool_t xdr_myString ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
