/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arguments {
	int a;
	int b;
};
typedef struct arguments arguments;

#define ZADANIE_1 0x23451111
#define ZADANIE_1_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(arguments *, CLIENT *);
extern  int * add_1_svc(arguments *, struct svc_req *);
extern int zadanie_1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
extern int zadanie_1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arguments (XDR *, arguments*);

#else /* K&R C */
extern bool_t xdr_arguments ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
